#!/bin/bash
cd /usr/lib/vdr/
touch *
cd /usr/src/reelbox/testing/packages/softcam/
touch *
make clean
if make all
  then
    echo "OK"
#    cd /usr/src/reelbox/testing/packages/softcam/
#    make clean
#    make all
    dpkg -i /usr/src/reelbox/testing/packages/softcam_*deb
    sudo service reelvdr stop
    sleep 6
    sudo chmod 775 /usr/lib/vdr/libvdr-sc.so.2.1.6
    rm /var/log/vdr-sc
    sudo service reelvdr start
    hwclock --show
else
    echo "error"
fi
