# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import sync_pb2
import extension_specifics_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='app_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x13\x61pp_specifics.proto\x12\x07sync_pb\x1a\nsync.proto\x1a\x19\x65xtension_specifics.proto\">\n\x0c\x41ppSpecifics\x12.\n\textension\x18\x01 \x01(\x0b\x32\x1b.sync_pb.ExtensionSpecifics:>\n\x03\x61pp\x12\x18.sync_pb.EntitySpecifics\x18\xec\xf9\x02 \x01(\x0b\x32\x15.sync_pb.AppSpecificsB\x04H\x03X\x01')


APP_FIELD_NUMBER = 48364
app = descriptor.FieldDescriptor(
  name='app', full_name='sync_pb.app', index=0,
  number=48364, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_APPSPECIFICS = descriptor.Descriptor(
  name='AppSpecifics',
  full_name='sync_pb.AppSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='extension', full_name='sync_pb.AppSpecifics.extension', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=133,
)

_APPSPECIFICS.fields_by_name['extension'].message_type = extension_specifics_pb2._EXTENSIONSPECIFICS
DESCRIPTOR.message_types_by_name['AppSpecifics'] = _APPSPECIFICS

class AppSpecifics(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPSPECIFICS
  
  # @@protoc_insertion_point(class_scope:sync_pb.AppSpecifics)

app.message_type = _APPSPECIFICS
sync_pb2.EntitySpecifics.RegisterExtension(app)
# @@protoc_insertion_point(module_scope)
