/* Automatically generated by configure - do not modify! */

#ifndef XINELIBOUTPUT_FEATURES_H
#define XINELIBOUTPUT_FEATURES_H

#define HAVE_X11 1
#define HAVE_FB 1
#define HAVE_VDR 1
#define HAVE_LIBXINE 1
#undef  HAVE_LIBEXTRACTOR
#define HAVE_LIBAVUTIL 1
#define HAVE_LIBJPEG 1
#define HAVE_DBUS_GLIB_1 1
#define HAVE_XSHM 1
#define HAVE_XDPMS 1
#define HAVE_XINERAMA 1
#define HAVE_XRENDER 1
#define HAVE_XSHAPE 1
#define HAVE_OPENGL 1
#define HAVE_PTHREAD 1
#define HAVE_DLFCN 1
#undef  HAVE_VDPAU
#define HAVE_I18N 1
#define HAVE_LIBCAP 1
#undef  HAVE_LIBBLURAY
#undef  HAVE_MCE_DBUS_NAMES

#endif /* XINELIBOUTPUT_FEATURES_H */
