# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import auth_pb2
import control_pb2
import event_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='internal.proto',
  package='remoting.protocol',
  serialized_pb='\n\x0einternal.proto\x12\x11remoting.protocol\x1a\nauth.proto\x1a\rcontrol.proto\x1a\x0b\x65vent.proto\"\xa0\x01\n\x0e\x43ontrolMessage\x12\x45\n\x15\x62\x65gin_session_request\x18\x03 \x01(\x0b\x32&.remoting.protocol.BeginSessionRequest\x12G\n\x16\x62\x65gin_session_response\x18\x04 \x01(\x0b\x32\'.remoting.protocol.BeginSessionResponse\"\x9a\x01\n\x0c\x45ventMessage\x12\x17\n\x0fsequence_number\x18\x01 \x02(\x03\x12\r\n\x05\x64ummy\x18\x02 \x01(\x08\x12.\n\tkey_event\x18\x03 \x01(\x0b\x32\x1b.remoting.protocol.KeyEvent\x12\x32\n\x0bmouse_event\x18\x04 \x01(\x0b\x32\x1d.remoting.protocol.MouseEventB\x02H\x03')




_CONTROLMESSAGE = descriptor.Descriptor(
  name='ControlMessage',
  full_name='remoting.protocol.ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='begin_session_request', full_name='remoting.protocol.ControlMessage.begin_session_request', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='begin_session_response', full_name='remoting.protocol.ControlMessage.begin_session_response', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=238,
)


_EVENTMESSAGE = descriptor.Descriptor(
  name='EventMessage',
  full_name='remoting.protocol.EventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sequence_number', full_name='remoting.protocol.EventMessage.sequence_number', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy', full_name='remoting.protocol.EventMessage.dummy', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key_event', full_name='remoting.protocol.EventMessage.key_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mouse_event', full_name='remoting.protocol.EventMessage.mouse_event', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=395,
)

_CONTROLMESSAGE.fields_by_name['begin_session_request'].message_type = auth_pb2._BEGINSESSIONREQUEST
_CONTROLMESSAGE.fields_by_name['begin_session_response'].message_type = auth_pb2._BEGINSESSIONRESPONSE
_EVENTMESSAGE.fields_by_name['key_event'].message_type = event_pb2._KEYEVENT
_EVENTMESSAGE.fields_by_name['mouse_event'].message_type = event_pb2._MOUSEEVENT
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE
DESCRIPTOR.message_types_by_name['EventMessage'] = _EVENTMESSAGE

class ControlMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLMESSAGE
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.ControlMessage)

class EventMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTMESSAGE
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.EventMessage)

# @@protoc_insertion_point(module_scope)
