netcv: netcvupdate.c File Reference
netcvupdate.c File Reference
#include "headers.h"
Macros
#define USE_MCLI_API
#define STATE_FILE "update.log"
#define FTP_CMD "ftp"
#define NC_CONFPATH "/mmc/etc/"
#define NC_CONFFILE "netceiver.conf"
#define API_WAIT_RESPONSE(cmd)
#define MAX_FWS 64
Functions
int api_init (char *path)
void add_upload (char *cmd, char *localfile, char *remotepath, char *remotefile)
void add_download (char *cmd, char *remotepath, char *remotefile)
int script_interpreter (char *script, char *line, char *ip, char *iface, char *user, char *pwd)
int generate_script (char *filename, char *tmpname, char *ip, char *iface, char *user, char *pwd)
int check_state_file (char *tmpname)
void sigground (int x)
int run_ftp (char *tmpdir, char *script, int timeout, char *pipeout)
int do_reboot (char *tmpdir, char *ip, char *iface, char *user, char *pwd)
int do_list_fw (char *tmpdir, char *ip, char *iface, char *user, char *pwd, int maxf, int *found, char **versions)
int do_kill (char *tmpdir, char *ip, char *iface, char *user, char *pwd)
int do_single_update (char *tmpdir, char *uuid, char *device)
int do_single_upload (char *uuid, char *device, char *remote_path, char *fname, char *remote_file)
int do_single_download (char *uuid, char *device, char *remote_path, char *fname)
int fw_action (char *uuid, char *iface, char *user, char *pwd, int mode, char *version)
int cleanup (char *tmpdir)
int unpack (char *tmpdir, char *file)
int check_xml (char *file)
int check_integrity (char *tmpdir)
int do_update (char **uuids, int num_uuids, char *device, char *optarg)
int do_upload (char **uuids, int num_uuids, char *device, char *optarg)
int do_download (char **uuids, int num_uuids, char *device, char *remotepath, char *file)
int do_all_reboot (char **uuids, int num_uuids, char *device)
int do_all_kill (char **uuids, int num_uuids, char *device)
int get_uuids (char **uuids, int max)
int show_uuids (void)
void show_firmwares (char *uuid, char *device, char *username, char *passwd)
int show_all_firmwares (char **uuids, int num_uuids)
void do_fw_actions (char **uuids, int max, int mode, char *version)
void usage (void)
int main (int argc, char **argv)
Variables
char ftp_cmd [512] =FTP_CMD
int verbose =0
int no_reboot =0
char username [256] ="root"
char password [256] ="root"
char device [256] ="eth0"
char * uuids [256] ={0}
char * versions [256] ={0}
int num_uuids =0
char socket_path [256] =API_SOCK_NAMESPACE
int sock_comm
char script [128 *1024]
Macro Definition Documentation
#define API_WAIT_RESPONSE (cmd)
Value:
{ cmd->state=API_REQUEST; \
                send (sock_comm, &sock_cmd, sizeof(api_cmd_t), 0); \
                recv (sock_comm, &sock_cmd, sizeof(api_cmd_t), 0); \
                if (cmd->state == API_ERROR) {warn ( "SHM parameter error, incompatible versions?\n"); exit(-1);}}
Definition at line 48 of file netcvupdate.c.
Referenced by get_uuids(), show_it(), and show_stats().
#define FTP_CMD "ftp"
Definition at line 31 of file netcvupdate.c.
#define MAX_FWS 64
Definition at line 612 of file netcvupdate.c.
Referenced by show_firmwares().
#define NC_CONFFILE "netceiver.conf"
Definition at line 33 of file netcvupdate.c.
Referenced by do_upload(), and main().
#define NC_CONFPATH "/mmc/etc/"
Definition at line 32 of file netcvupdate.c.
Referenced by main().
#define STATE_FILE "update.log"
Definition at line 30 of file netcvupdate.c.
#define USE_MCLI_API
Definition at line 12 of file netcvupdate.c.
Function Documentation
void add_download (char * cmd, char * remotepath, char * remotefile)
Definition at line 93 of file netcvupdate.c.
Referenced by script_interpreter().
void add_upload (char * cmd, char * localfile, char * remotepath, char * remotefile)
Definition at line 82 of file netcvupdate.c.
Referenced by script_interpreter().
int api_init (char * path)
Definition at line 55 of file netcvupdate.c.
References sock_comm.
Referenced by get_uuids().
int check_integrity (char * tmpdir)
Definition at line 423 of file netcvupdate.c.
Referenced by do_update().
int check_state_file (char * tmpname)
Definition at line 163 of file netcvupdate.c.
Referenced by do_single_update().
int check_xml (char * file)
Definition at line 413 of file netcvupdate.c.
Referenced by do_upload().
int cleanup (char * tmpdir)
Definition at line 393 of file netcvupdate.c.
Referenced by do_update().
int do_all_kill (char ** uuids, int num_uuids, char * device)
Definition at line 547 of file netcvupdate.c.
References do_kill(), num_uuids, password, and username.
Referenced by main().
int do_all_reboot (char ** uuids, int num_uuids, char * device)
Definition at line 529 of file netcvupdate.c.
References do_reboot(), num_uuids, password, and username.
Referenced by main().
int do_download (char ** uuids, int num_uuids, char * device, char * remotepath, char * file)
Definition at line 499 of file netcvupdate.c.
References do_single_download(), and num_uuids.
Referenced by main().
void do_fw_actions (char ** uuids, int max, int mode, char * version)
Definition at line 647 of file netcvupdate.c.
References device, fw_action(), password, show_firmwares(), and username.
Referenced by main().
int do_kill (char * tmpdir, char * ip, char * iface, char * user, char * pwd)
Definition at line 275 of file netcvupdate.c.
References run_ftp(), and script.
Referenced by do_all_kill().
int do_list_fw (char * tmpdir, char * ip, char * iface, char * user, char * pwd, int maxf, int * found, char ** versions)
Definition at line 213 of file netcvupdate.c.
References run_ftp(), and script.
Referenced by show_firmwares().
int do_reboot (char * tmpdir, char * ip, char * iface, char * user, char * pwd)
Definition at line 200 of file netcvupdate.c.
References run_ftp(), and script.
Referenced by do_all_reboot(), and do_single_update().
int do_single_download (char * uuid, char * device, char * remote_path, char * fname)
Definition at line 337 of file netcvupdate.c.
References password, run_ftp(), script, and username.
Referenced by do_download().
int do_single_update (char * tmpdir, char * uuid, char * device)
Definition at line 287 of file netcvupdate.c.
References check_state_file(), do_reboot(), generate_script(), no_reboot, password, run_ftp(), script, and username.
Referenced by do_update().
int do_single_upload (char * uuid, char * device, char * remote_path, char * fname, char * remote_file)
Definition at line 322 of file netcvupdate.c.
References password, run_ftp(), script, and username.
Referenced by do_upload().
int do_update (char ** uuids, int num_uuids, char * device, char * optarg)
Definition at line 433 of file netcvupdate.c.
References check_integrity(), cleanup(), do_single_update(), num_uuids, and unpack().
Referenced by main().
int do_upload (char ** uuids, int num_uuids, char * device, char * optarg)
Definition at line 474 of file netcvupdate.c.
References check_xml(), do_single_upload(), NC_CONFFILE, and num_uuids.
Referenced by main().
int fw_action (char * uuid, char * iface, char * user, char * pwd, int mode, char * version)
Definition at line 351 of file netcvupdate.c.
References device, password, run_ftp(), script, and username.
Referenced by do_fw_actions().
int generate_script (char * filename, char * tmpname, char * ip, char * iface, char * user, char * pwd)
Definition at line 141 of file netcvupdate.c.
References script, and script_interpreter().
Referenced by do_single_update().
int get_uuids (char ** uuids, int max)
Definition at line 565 of file netcvupdate.c.
References api_init(), API_WAIT_RESPONSE, socket_path, and versions.
Referenced by main(), and show_uuids().
int main (int argc, char ** argv)
Definition at line 703 of file netcvupdate.c.
References device, do_all_kill(), do_all_reboot(), do_download(), do_fw_actions(), do_update(), do_upload(), ftp_cmd, get_uuids(), NC_CONFFILE, NC_CONFPATH, no_reboot, num_uuids, password, show_all_firmwares(), show_uuids(), socket_path, usage(), username, uuids, and verbose.
int run_ftp (char * tmpdir, char * script, int timeout, char * pipeout)
Definition at line 178 of file netcvupdate.c.
References ftp_cmd, sigground(), and verbose.
Referenced by do_kill(), do_list_fw(), do_reboot(), do_single_download(), do_single_update(), do_single_upload(), and fw_action().
int script_interpreter (char * script, char * line, char * ip, char * iface, char * user, char * pwd)
Definition at line 103 of file netcvupdate.c.
References add_download(), and add_upload().
Referenced by generate_script().
int show_all_firmwares (char ** uuids, int num_uuids)
Definition at line 635 of file netcvupdate.c.
References device, num_uuids, password, show_firmwares(), and username.
Referenced by main().
void show_firmwares (char * uuid, char * device, char * username, char * passwd)
Definition at line 613 of file netcvupdate.c.
References do_list_fw(), MAX_FWS, password, and versions.
Referenced by do_fw_actions(), and show_all_firmwares().
int show_uuids (void)
Definition at line 599 of file netcvupdate.c.
References get_uuids(), num_uuids, uuids, and versions.
Referenced by main().
void sigground (int x)
Definition at line 174 of file netcvupdate.c.
Referenced by run_ftp().
int unpack (char * tmpdir, char * file)
Definition at line 403 of file netcvupdate.c.
Referenced by do_update().
void usage (void)
Definition at line 669 of file netcvupdate.c.
Referenced by main().
Variable Documentation
char device[256] ="eth0"
Definition at line 40 of file netcvupdate.c.
Referenced by do_fw_actions(), fw_action(), main(), and show_all_firmwares().
char ftp_cmd[512] =FTP_CMD
Definition at line 35 of file netcvupdate.c.
Referenced by main(), and run_ftp().
int no_reboot =0
Definition at line 37 of file netcvupdate.c.
Referenced by do_single_update(), and main().
int num_uuids =0
Definition at line 43 of file netcvupdate.c.
Referenced by do_all_kill(), do_all_reboot(), do_download(), do_update(), do_upload(), main(), show_all_firmwares(), and show_uuids().
char password[256] ="root"
Definition at line 39 of file netcvupdate.c.
Referenced by do_all_kill(), do_all_reboot(), do_fw_actions(), do_single_download(), do_single_update(), do_single_upload(), fw_action(), main(), show_all_firmwares(), and show_firmwares().
char script[128 *1024]
Definition at line 140 of file netcvupdate.c.
Referenced by do_kill(), do_list_fw(), do_reboot(), do_single_download(), do_single_update(), do_single_upload(), fw_action(), and generate_script().
int sock_comm
Definition at line 53 of file netcvupdate.c.
Referenced by api_init().
char socket_path[256] =API_SOCK_NAMESPACE
Definition at line 44 of file netcvupdate.c.
Referenced by get_uuids(), and main().
char username[256] ="root"
Definition at line 38 of file netcvupdate.c.
Referenced by do_all_kill(), do_all_reboot(), do_fw_actions(), do_single_download(), do_single_update(), do_single_upload(), fw_action(), main(), and show_all_firmwares().
char* uuids[256] ={0}
Definition at line 41 of file netcvupdate.c.
Referenced by main(), and show_uuids().
int verbose =0
Definition at line 36 of file netcvupdate.c.
Referenced by main(), and run_ftp().
char* versions[256] ={0}
Definition at line 42 of file netcvupdate.c.
Referenced by get_uuids(), show_firmwares(), and show_uuids().