netcv: netcvdiag.c File Reference
netcvdiag.c File Reference
#include "headers.h"
Functions
void usage (void)
void show_it (int show_count, int show_uuids, int show_tuners, int show_sats, int show_versions, int show_cams)
void show_stats (void)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 359 of file netcvdiag.c.
References show_it(), show_stats(), show_uuids(), and usage().
void show_it (int show_count, int show_uuids, int show_tuners, int show_sats, int show_versions, int show_cams)
Definition at line 93 of file netcvdiag.c.
References API_WAIT_RESPONSE.
Referenced by main().
void show_stats (void)
Definition at line 284 of file netcvdiag.c.
References API_WAIT_RESPONSE.
Referenced by main().
void usage (void)
Definition at line 74 of file netcvdiag.c.
Referenced by main().