# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='csd.proto',
  package='safe_browsing',
  serialized_pb='\n\tcsd.proto\x12\rsafe_browsing\"\xd2\x02\n\x15\x43lientPhishingRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bhash_prefix\x18\n \x01(\x0c\x12\x14\n\x0c\x63lient_score\x18\x02 \x02(\x02\x12\x13\n\x0bis_phishing\x18\x04 \x01(\x08\x12\x41\n\x0b\x66\x65\x61ture_map\x18\x05 \x03(\x0b\x32,.safe_browsing.ClientPhishingRequest.Feature\x12\x15\n\rmodel_version\x18\x06 \x01(\x05\x12K\n\x15non_model_feature_map\x18\x08 \x03(\x0b\x32,.safe_browsing.ClientPhishingRequest.Feature\x12\x1d\n\x15OBSOLETE_referrer_url\x18\t \x01(\t\x1a&\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x01\"F\n\x16\x43lientPhishingResponse\x12\x0e\n\x06phishy\x18\x01 \x02(\x08\x12\x1c\n\x14whitelist_expression\x18\x02 \x03(\tB\x02H\x03')




_CLIENTPHISHINGREQUEST_FEATURE = descriptor.Descriptor(
  name='Feature',
  full_name='safe_browsing.ClientPhishingRequest.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='safe_browsing.ClientPhishingRequest.Feature.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='safe_browsing.ClientPhishingRequest.Feature.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=329,
  serialized_end=367,
)

_CLIENTPHISHINGREQUEST = descriptor.Descriptor(
  name='ClientPhishingRequest',
  full_name='safe_browsing.ClientPhishingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='safe_browsing.ClientPhishingRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hash_prefix', full_name='safe_browsing.ClientPhishingRequest.hash_prefix', index=1,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_score', full_name='safe_browsing.ClientPhishingRequest.client_score', index=2,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_phishing', full_name='safe_browsing.ClientPhishingRequest.is_phishing', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='feature_map', full_name='safe_browsing.ClientPhishingRequest.feature_map', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='model_version', full_name='safe_browsing.ClientPhishingRequest.model_version', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='non_model_feature_map', full_name='safe_browsing.ClientPhishingRequest.non_model_feature_map', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='OBSOLETE_referrer_url', full_name='safe_browsing.ClientPhishingRequest.OBSOLETE_referrer_url', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTPHISHINGREQUEST_FEATURE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=367,
)


_CLIENTPHISHINGRESPONSE = descriptor.Descriptor(
  name='ClientPhishingResponse',
  full_name='safe_browsing.ClientPhishingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='phishy', full_name='safe_browsing.ClientPhishingResponse.phishy', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='whitelist_expression', full_name='safe_browsing.ClientPhishingResponse.whitelist_expression', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=369,
  serialized_end=439,
)

_CLIENTPHISHINGREQUEST_FEATURE.containing_type = _CLIENTPHISHINGREQUEST;
_CLIENTPHISHINGREQUEST.fields_by_name['feature_map'].message_type = _CLIENTPHISHINGREQUEST_FEATURE
_CLIENTPHISHINGREQUEST.fields_by_name['non_model_feature_map'].message_type = _CLIENTPHISHINGREQUEST_FEATURE
DESCRIPTOR.message_types_by_name['ClientPhishingRequest'] = _CLIENTPHISHINGREQUEST
DESCRIPTOR.message_types_by_name['ClientPhishingResponse'] = _CLIENTPHISHINGRESPONSE

class ClientPhishingRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Feature(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTPHISHINGREQUEST_FEATURE
    
    # @@protoc_insertion_point(class_scope:safe_browsing.ClientPhishingRequest.Feature)
  DESCRIPTOR = _CLIENTPHISHINGREQUEST
  
  # @@protoc_insertion_point(class_scope:safe_browsing.ClientPhishingRequest)

class ClientPhishingResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTPHISHINGRESPONSE
  
  # @@protoc_insertion_point(class_scope:safe_browsing.ClientPhishingResponse)

# @@protoc_insertion_point(module_scope)
