/* Automatically generated by configure - do not modify! */

#ifndef XINELIBOUTPUT_FEATURES_H
#define XINELIBOUTPUT_FEATURES_H

#define HAVE_X11 1
#define HAVE_FB 1
#define HAVE_VDR 1
#define HAVE_LIBXINE 1
#define HAVE_LIBEXTRACTOR 1
#define HAVE_LIBAVUTIL 1
#define HAVE_LIBJPEG 1
#define HAVE_DBUS_GLIB_1 1
#define HAVE_XSHM 1
#define HAVE_XDPMS 1
#define HAVE_XINERAMA 1
#define HAVE_XRENDER 1
#define HAVE_XSHAPE 1
#define HAVE_OPENGL 1
#define HAVE_PTHREAD 1
#define HAVE_DLFCN 1
#define HAVE_VDPAU 1
#define HAVE_I18N 1
#define HAVE_LIBCAP 1
#define HAVE_LIBBLURAY 1
#define HAVE_MCE_DBUS_NAMES 1

#endif /* XINELIBOUTPUT_FEATURES_H */
