# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='auth.proto',
  package='remoting.protocol',
  serialized_pb='\n\nauth.proto\x12\x11remoting.protocol\"]\n\x0f\x43lientAuthToken\x12\x15\n\rhost_full_jid\x18\x01 \x01(\t\x12\x17\n\x0f\x63lient_full_jid\x18\x02 \x01(\t\x12\x1a\n\x12\x63lient_oauth_token\x18\x03 \x01(\t\"n\n\x15LocalLoginCredentials\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.remoting.protocol.CredentialType\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\x0c\"S\n\x10LocalLoginStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1a\n\x0ftries_remaining\x18\x02 \x01(\x05:\x01\x30\x12\x12\n\nerror_info\x18\x03 \x01(\t\"\x8e\x01\n\x14LocalLoginProperties\x12\x45\n\x1asupported_credential_types\x18\x01 \x03(\x0e\x32!.remoting.protocol.CredentialType\x12\x17\n\x0f\x61ntiphish_image\x18\x02 \x01(\x0c\x12\x16\n\x0e\x61ntiphish_text\x18\x03 \x01(\x0c\"T\n\x13\x42\x65ginSessionRequest\x12=\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32(.remoting.protocol.LocalLoginCredentials\"Q\n\x14\x42\x65ginSessionResponse\x12\x39\n\x0clogin_status\x18\x01 \x01(\x0b\x32#.remoting.protocol.LocalLoginStatus*\x1e\n\x0e\x43redentialType\x12\x0c\n\x08PASSWORD\x10\x00\x42\x02H\x03')

_CREDENTIALTYPE = descriptor.EnumDescriptor(
  name='CredentialType',
  full_name='remoting.protocol.CredentialType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PASSWORD', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=639,
  serialized_end=669,
)


PASSWORD = 0



_CLIENTAUTHTOKEN = descriptor.Descriptor(
  name='ClientAuthToken',
  full_name='remoting.protocol.ClientAuthToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='host_full_jid', full_name='remoting.protocol.ClientAuthToken.host_full_jid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_full_jid', full_name='remoting.protocol.ClientAuthToken.client_full_jid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_oauth_token', full_name='remoting.protocol.ClientAuthToken.client_oauth_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=126,
)


_LOCALLOGINCREDENTIALS = descriptor.Descriptor(
  name='LocalLoginCredentials',
  full_name='remoting.protocol.LocalLoginCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='remoting.protocol.LocalLoginCredentials.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='username', full_name='remoting.protocol.LocalLoginCredentials.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='credential', full_name='remoting.protocol.LocalLoginCredentials.credential', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=128,
  serialized_end=238,
)


_LOCALLOGINSTATUS = descriptor.Descriptor(
  name='LocalLoginStatus',
  full_name='remoting.protocol.LocalLoginStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='remoting.protocol.LocalLoginStatus.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tries_remaining', full_name='remoting.protocol.LocalLoginStatus.tries_remaining', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_info', full_name='remoting.protocol.LocalLoginStatus.error_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=240,
  serialized_end=323,
)


_LOCALLOGINPROPERTIES = descriptor.Descriptor(
  name='LocalLoginProperties',
  full_name='remoting.protocol.LocalLoginProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='supported_credential_types', full_name='remoting.protocol.LocalLoginProperties.supported_credential_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='antiphish_image', full_name='remoting.protocol.LocalLoginProperties.antiphish_image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='antiphish_text', full_name='remoting.protocol.LocalLoginProperties.antiphish_text', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=326,
  serialized_end=468,
)


_BEGINSESSIONREQUEST = descriptor.Descriptor(
  name='BeginSessionRequest',
  full_name='remoting.protocol.BeginSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='credentials', full_name='remoting.protocol.BeginSessionRequest.credentials', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=470,
  serialized_end=554,
)


_BEGINSESSIONRESPONSE = descriptor.Descriptor(
  name='BeginSessionResponse',
  full_name='remoting.protocol.BeginSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='login_status', full_name='remoting.protocol.BeginSessionResponse.login_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=556,
  serialized_end=637,
)

_LOCALLOGINCREDENTIALS.fields_by_name['type'].enum_type = _CREDENTIALTYPE
_LOCALLOGINPROPERTIES.fields_by_name['supported_credential_types'].enum_type = _CREDENTIALTYPE
_BEGINSESSIONREQUEST.fields_by_name['credentials'].message_type = _LOCALLOGINCREDENTIALS
_BEGINSESSIONRESPONSE.fields_by_name['login_status'].message_type = _LOCALLOGINSTATUS
DESCRIPTOR.message_types_by_name['ClientAuthToken'] = _CLIENTAUTHTOKEN
DESCRIPTOR.message_types_by_name['LocalLoginCredentials'] = _LOCALLOGINCREDENTIALS
DESCRIPTOR.message_types_by_name['LocalLoginStatus'] = _LOCALLOGINSTATUS
DESCRIPTOR.message_types_by_name['LocalLoginProperties'] = _LOCALLOGINPROPERTIES
DESCRIPTOR.message_types_by_name['BeginSessionRequest'] = _BEGINSESSIONREQUEST
DESCRIPTOR.message_types_by_name['BeginSessionResponse'] = _BEGINSESSIONRESPONSE

class ClientAuthToken(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTAUTHTOKEN
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.ClientAuthToken)

class LocalLoginCredentials(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALLOGINCREDENTIALS
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.LocalLoginCredentials)

class LocalLoginStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALLOGINSTATUS
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.LocalLoginStatus)

class LocalLoginProperties(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALLOGINPROPERTIES
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.LocalLoginProperties)

class BeginSessionRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BEGINSESSIONREQUEST
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.BeginSessionRequest)

class BeginSessionResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BEGINSESSIONRESPONSE
  
  # @@protoc_insertion_point(class_scope:remoting.protocol.BeginSessionResponse)

# @@protoc_insertion_point(module_scope)
