# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='control.proto',
  package='remoting.protocol',
  serialized_pb='\n\rcontrol.proto\x12\x11remoting.protocolB\x02H\x03')




# @@protoc_insertion_point(module_scope)
